server:
  port: 8769
spring:
  application:
    name: smartpark-base
  rabbitmq:
    host: localhost
    port: 5672
    username: wym
    password: wym
    listener:
      direct:
        acknowledge-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}