server:
  port: 8863
spring:
  application:
    name: smartpark-base
  rabbitmq:
    host: localhost
    port: 5672
    username: wym
    password: wym
    listener:
      direct:
        acknowledge-mode: manual
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/smart_park_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true


#swagger:
#  butler:
#    api-docs-path: "/v2/api-docs"
#    swagger-version: 2.0
#    resources:
#      user:
#        name: "user-service"




  eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml